/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIndexRouteImport } from './routes/$room/index'
import { Route as RoomSecretRouteImport } from './routes/$room/$secret'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/$room/',
  path: '/$room/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSecretRoute = RoomSecretRouteImport.update({
  id: '/$room/$secret',
  path: '/$room/$secret',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$room/$secret': typeof RoomSecretRoute
  '/$room/': typeof RoomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$room/$secret': typeof RoomSecretRoute
  '/$room': typeof RoomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$room/$secret': typeof RoomSecretRoute
  '/$room/': typeof RoomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$room/$secret' | '/$room/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$room/$secret' | '/$room'
  id: '__root__' | '/' | '/$room/$secret' | '/$room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomSecretRoute: typeof RoomSecretRoute
  RoomIndexRoute: typeof RoomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$room/': {
      id: '/$room/'
      path: '/$room'
      fullPath: '/$room/'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$room/$secret': {
      id: '/$room/$secret'
      path: '/$room/$secret'
      fullPath: '/$room/$secret'
      preLoaderRoute: typeof RoomSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomSecretRoute: RoomSecretRoute,
  RoomIndexRoute: RoomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
